// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auditorium.get.sql

package sqlc

import (
	"context"
)

const isAuditoriumExist = `-- name: IsAuditoriumExist :one
SELECT EXISTS (
    SELECT 1 FROM "auditoriums" WHERE id = $1 AND is_released = true
) AS exists
`

func (q *Queries) IsAuditoriumExist(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, isAuditoriumExist, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
