// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: fab_info.create.sql

package sqlc

import (
	"context"
)

const createNewFABInfo = `-- name: CreateNewFABInfo :exec
INSERT INTO fab_infos (
    fab_id,
    price
)
VALUES (
    $1, $2
)
`

type CreateNewFABInfoParams struct {
	FabID int32 `json:"fab_id"`
	Price int32 `json:"price"`
}

func (q *Queries) CreateNewFABInfo(ctx context.Context, arg CreateNewFABInfoParams) error {
	_, err := q.db.Exec(ctx, createNewFABInfo, arg.FabID, arg.Price)
	return err
}
