// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: film_id.create.sql

package sqlc

import (
	"context"
)

const createNewFilmId = `-- name: CreateNewFilmId :exec
INSERT INTO film_ids (
    film_id
)
VALUES (
    $1
)
`

func (q *Queries) CreateNewFilmId(ctx context.Context, filmID int32) error {
	_, err := q.db.Exec(ctx, createNewFilmId, filmID)
	return err
}
