// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: film_id.create.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNewFilmId = `-- name: CreateNewFilmId :exec
INSERT INTO film_infos (
    film_id,
    duration
)
VALUES (
    $1, $2
)
`

type CreateNewFilmIdParams struct {
	FilmID   int32           `json:"film_id"`
	Duration pgtype.Interval `json:"duration"`
}

func (q *Queries) CreateNewFilmId(ctx context.Context, arg CreateNewFilmIdParams) error {
	_, err := q.db.Exec(ctx, createNewFilmId, arg.FilmID, arg.Duration)
	return err
}
