// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: film_id.get.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDuration = `-- name: GetDuration :one
SELECT duration
FROM film_infos
WHERE film_id = $1
`

func (q *Queries) GetDuration(ctx context.Context, filmID int32) (pgtype.Interval, error) {
	row := q.db.QueryRow(ctx, getDuration, filmID)
	var duration pgtype.Interval
	err := row.Scan(&duration)
	return duration, err
}

const isFilmIdExist = `-- name: IsFilmIdExist :one
SELECT EXISTS (
    SELECT 1 FROM "film_infos" WHERE film_id = $1
) AS EXISTS
`

func (q *Queries) IsFilmIdExist(ctx context.Context, filmID int32) (bool, error) {
	row := q.db.QueryRow(ctx, isFilmIdExist, filmID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
