// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: film_id.get.sql

package sqlc

import (
	"context"
)

const isFilmIdExist = `-- name: IsFilmIdExist :one
SELECT EXISTS (
    SELECT 1 FROM "film_ids" WHERE id = $1
) AS exists
`

func (q *Queries) IsFilmIdExist(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, isFilmIdExist, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
