// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: outbox.create.sql

package sqlc

import (
	"context"
)

const createOutbox = `-- name: CreateOutbox :exec
INSERT INTO outboxes (
    aggregated_type,
    aggregated_id,
    event_type,
    payload
) VALUES (
    $1, $2, $3, $4
)
`

type CreateOutboxParams struct {
	AggregatedType string `json:"aggregated_type"`
	AggregatedID   int32  `json:"aggregated_id"`
	EventType      string `json:"event_type"`
	Payload        []byte `json:"payload"`
}

func (q *Queries) CreateOutbox(ctx context.Context, arg CreateOutboxParams) error {
	_, err := q.db.Exec(ctx, createOutbox,
		arg.AggregatedType,
		arg.AggregatedID,
		arg.EventType,
		arg.Payload,
	)
	return err
}
