// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateNewFilmId(ctx context.Context, arg CreateNewFilmIdParams) error
	CreateShowTime(ctx context.Context, arg CreateShowTimeParams) error
	GetAllShowTimesByFilmIdInOneDate(ctx context.Context, arg GetAllShowTimesByFilmIdInOneDateParams) ([]Showtimes, error)
	GetAllShowtimeSeatsByShowtimeId(ctx context.Context, showtimeID int32) ([]ShowtimeSeats, error)
	GetDuration(ctx context.Context, filmID int32) (pgtype.Interval, error)
	GetLatestShowtimeByAuditoriumId(ctx context.Context, arg GetLatestShowtimeByAuditoriumIdParams) (pgtype.Timestamp, error)
	GetShowdateByShowtimeId(ctx context.Context, id int32) (pgtype.Date, error)
	GetShowtimeById(ctx context.Context, id int32) (Showtimes, error)
	IsAuditoriumExist(ctx context.Context, id int32) (bool, error)
	IsFilmIdExist(ctx context.Context, id int32) (bool, error)
	IsShowtimeExist(ctx context.Context, id int32) (bool, error)
	UpdateShowtimeSeatSeatByIdAndShowtimeId(ctx context.Context, arg UpdateShowtimeSeatSeatByIdAndShowtimeIdParams) error
	createShowtimeSeats(ctx context.Context, showtimeID int32) error
	isShowtimeRealeased(ctx context.Context, id int32) (bool, error)
	releaseShowtime(ctx context.Context, id int32) error
	updateShowtime(ctx context.Context, arg updateShowtimeParams) error
}

var _ Querier = (*Queries)(nil)
