// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: seat.get.sql

package sqlc

import (
	"context"
)

const getPriceOfSeatBySeatId = `-- name: GetPriceOfSeatBySeatId :one
SELECT price
FROM seats
WHERE id = $1
`

func (q *Queries) GetPriceOfSeatBySeatId(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, getPriceOfSeatBySeatId, id)
	var price int32
	err := row.Scan(&price)
	return price, err
}
