// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: showtime.update.sql

package sqlc

import (
	"context"
)

const turnOnShowtime = `-- name: TurnOnShowtime :exec
UPDATE showtimes
SET is_deleted = true,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) TurnOnShowtime(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, turnOnShowtime, id)
	return err
}
