// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: showtime_seat.create.sql

package sqlc

import (
	"context"
)

const createShowtimeSeats = `-- name: createShowtimeSeats :exec
INSERT INTO showtime_seats (showtime_id, seat_id, status, created_at)
SELECT
    $1 AS showtime_id,
    s.id AS seat_id,
    'available'::seat_statuses AS status,
    now()
FROM
    showtimes sh
JOIN
    seats s ON s.auditorium_id = sh.auditorium_id
WHERE
    sh.id = $1
`

func (q *Queries) createShowtimeSeats(ctx context.Context, showtimeID int32) error {
	_, err := q.db.Exec(ctx, createShowtimeSeats, showtimeID)
	return err
}
