// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: showtime.create.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShowTime = `-- name: CreateShowTime :exec
INSERT INTO showtimes (
    film_id,
    auditorium_id,
    changed_by,
    show_date,
    start_time,
    end_time
)
VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreateShowTimeParams struct {
	FilmID       int32            `json:"film_id"`
	AuditoriumID int32            `json:"auditorium_id"`
	ChangedBy    string           `json:"changed_by"`
	ShowDate     pgtype.Date      `json:"show_date"`
	StartTime    pgtype.Timestamp `json:"start_time"`
	EndTime      pgtype.Timestamp `json:"end_time"`
}

func (q *Queries) CreateShowTime(ctx context.Context, arg CreateShowTimeParams) error {
	_, err := q.db.Exec(ctx, createShowTime,
		arg.FilmID,
		arg.AuditoriumID,
		arg.ChangedBy,
		arg.ShowDate,
		arg.StartTime,
		arg.EndTime,
	)
	return err
}
