// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: showtime_seat.update.sql

package sqlc

import (
	"context"
)

const updateShowtimeSeatById = `-- name: UpdateShowtimeSeatById :exec
UPDATE showtime_seats
SET status = $2,
    booked_by = $3,
    booked_at = CASE WHEN $2 = 'booked' THEN NOW() ELSE NULL END
WHERE id = $1
`

type UpdateShowtimeSeatByIdParams struct {
	ID       int32        `json:"id"`
	Status   SeatStatuses `json:"status"`
	BookedBy string       `json:"booked_by"`
}

func (q *Queries) UpdateShowtimeSeatById(ctx context.Context, arg UpdateShowtimeSeatByIdParams) error {
	_, err := q.db.Exec(ctx, updateShowtimeSeatById, arg.ID, arg.Status, arg.BookedBy)
	return err
}
