// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: showtime_seat.get.sql

package sqlc

import (
	"context"
)

const getAllShowtimeSeatsByShowtimeId = `-- name: GetAllShowtimeSeatsByShowtimeId :many
SELECT id, showtime_id, seat_id, status, booked_by, created_at, booked_at
FROM showtime_seats
WHERE showtime_id = $1
`

func (q *Queries) GetAllShowtimeSeatsByShowtimeId(ctx context.Context, showtimeID int32) ([]ShowtimeSeats, error) {
	rows, err := q.db.Query(ctx, getAllShowtimeSeatsByShowtimeId, showtimeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShowtimeSeats{}
	for rows.Next() {
		var i ShowtimeSeats
		if err := rows.Scan(
			&i.ID,
			&i.ShowtimeID,
			&i.SeatID,
			&i.Status,
			&i.BookedBy,
			&i.CreatedAt,
			&i.BookedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
