// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: showtime_seat.update.sql

package sqlc

import (
	"context"
)

const updateShowtimeSeatSeatByIdAndShowtimeId = `-- name: UpdateShowtimeSeatSeatByIdAndShowtimeId :exec
UPDATE showtime_seats
SET status = $2,
    booked_by = $3,
    booked_at = CASE WHEN $2 = 'booked'::seat_statuses THEN NOW() ELSE NULL::timestamp END
WHERE seat_id = $1 AND showtime_id = $4
`

type UpdateShowtimeSeatSeatByIdAndShowtimeIdParams struct {
	SeatID     int32        `json:"seat_id"`
	Status     SeatStatuses `json:"status"`
	BookedBy   string       `json:"booked_by"`
	ShowtimeID int32        `json:"showtime_id"`
}

func (q *Queries) UpdateShowtimeSeatSeatByIdAndShowtimeId(ctx context.Context, arg UpdateShowtimeSeatSeatByIdAndShowtimeIdParams) error {
	_, err := q.db.Exec(ctx, updateShowtimeSeatSeatByIdAndShowtimeId,
		arg.SeatID,
		arg.Status,
		arg.BookedBy,
		arg.ShowtimeID,
	)
	return err
}
