// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injectors

import (
	"bmt_showtime_service/db/sqlc"
	"bmt_showtime_service/internal/controllers"
	"bmt_showtime_service/internal/implementaions/message_broker/readers"
	"bmt_showtime_service/internal/implementaions/redis"
	"bmt_showtime_service/internal/implementaions/showtime"
	"bmt_showtime_service/internal/implementaions/showtime_seat"
	"bmt_showtime_service/internal/injectors/provider"
)

// Injectors from message_broker.wire.go:

func InitMessageBroker() (*readers.MessageBrokerReader, error) {
	pool := provider.ProvidePgxPool()
	iStore := sqlc.NewStore(pool)
	iRedis := redis.NewRedisClient()
	messageBrokerReader := readers.NewMessageBrokerReader(iStore, iRedis)
	return messageBrokerReader, nil
}

// Injectors from showtime_controller.wire.go:

func InitShowtimeController() (*controllers.ShowtimeController, error) {
	pool := provider.ProvidePgxPool()
	iStore := sqlc.NewStore(pool)
	iRedis := redis.NewRedisClient()
	iShowtime := showtime.NewShowtimeService(iStore, iRedis)
	showtimeController := controllers.NewShowtimeController(iShowtime)
	return showtimeController, nil
}

// Injectors from showtime_seat_controller.wire.go:

func InitShowtimeSeatController() (*controllers.ShowtimeSeatController, error) {
	pool := provider.ProvidePgxPool()
	iStore := sqlc.NewStore(pool)
	iRedis := redis.NewRedisClient()
	iShowtimeSeat := showtimeseat.NewShowtimeSeatService(iStore, iRedis)
	showtimeSeatController := controllers.NewShowtimeSeatController(iShowtimeSeat)
	return showtimeSeatController, nil
}
